import Head from "next/head";
import { useState } from "react";
import Navbar from "@/components/navbar/Navbar";
import PdfUploader from "@/components/PdfUploader";
import ChatBot from "@/components/ChatBot";

export default function Pdf() {
  const [pdf, setPdf] = useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        {pdf ? <ChatBot /> : <PdfUploader />}
      </main>
    </>
  );
}
