import Head from 'next/head'
import Image from 'next/image'
import AiChat from "../components/aiChat/AiChat";
import BeginsWithQsn from "../components/beginsWithQsn/BeginsWithQsn";
import Footer from "../components/footer/Footer";
import PricingC from "../components/pricing/PricingC";
import UseCases from "../components/useCases/UseCases";
import Work from "../components/work/Work";
import Navbar from '@/components/navbar/Navbar';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <AiChat />
        <Work />
        <UseCases />
        <div
          className="d-flex justify-content-center align-items-center "
          style={{ marginTop: "15rem", marginBottom: "-8rem" }}
        >
          <PricingC />
        </div>
        <BeginsWithQsn />
        <Footer />
      </main>
    </>
  )
}
